"""Complete Domain Expansion

Revision ID: 21adcfd72d12
Revises: 629f76f8ccb2
Create Date: 2026-01-20 13:54:27.975178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg


# revision identifiers, used by Alembic.
revision: str = '21adcfd72d12'
down_revision: Union[str, Sequence[str], None] = '629f76f8ccb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create Enums manually (Idempotent)
    op.execute("DO $$ BEGIN CREATE TYPE recipestatus AS ENUM ('DRAFT', 'PUBLISHED', 'MODERATION'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE mealtype AS ENUM ('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE skilllevel AS ENUM ('BEGINNER', 'INTERMEDIATE', 'ADVANCED'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE entitytype AS ENUM ('RECIPE', 'COMMENT', 'USER'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE moderationaction AS ENUM ('APPROVE', 'REJECT', 'DELETE'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE reportstatus AS ENUM ('PENDING', 'RESOLVED'); EXCEPTION WHEN duplicate_object THEN null; END $$;")

    op.create_table('badges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipments_id'), 'equipments', ['id'], unique=False)
    op.create_index(op.f('ix_equipments_name'), 'equipments', ['name'], unique=True)
    op.create_table('levels',
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp_required', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('level')
    )
    op.create_table('tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('blocks',
    sa.Column('blocker_id', sa.String(), nullable=False),
    sa.Column('blocked_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id')
    )
    op.create_table('collections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_id'), 'collections', ['id'], unique=False)
    op.create_table('follows',
    sa.Column('follower_id', sa.String(), nullable=False),
    sa.Column('following_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'following_id')
    )
    op.create_table('moderation_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('target_type', pg.ENUM('RECIPE', 'COMMENT', 'USER', name='entitytype', create_type=False), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('moderator_id', sa.String(), nullable=False),
    sa.Column('action', pg.ENUM('APPROVE', 'REJECT', 'DELETE', name='moderationaction', create_type=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_logs_id'), 'moderation_logs', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reporter_id', sa.String(), nullable=False),
    sa.Column('target_type', pg.ENUM('RECIPE', 'COMMENT', 'USER', name='entitytype', create_type=False), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', pg.ENUM('PENDING', 'RESOLVED', name='reportstatus', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('search_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('searched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_logs_id'), 'search_logs', ['id'], unique=False)
    op.create_table('shopping_lists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_lists_id'), 'shopping_lists', ['id'], unique=False)
    op.create_index(op.f('ix_shopping_lists_user_id'), 'shopping_lists', ['user_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('badge_id', sa.String(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'badge_id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('skill_level', pg.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='skilllevel', create_type=False), nullable=True),
    sa.Column('dietary_restrictions', sa.Text(), nullable=True),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('collection_recipes',
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'recipe_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_table('cook_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('cooked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cook_logs_id'), 'cook_logs', ['id'], unique=False)
    op.create_table('instruction_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('timer_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruction_steps_id'), 'instruction_steps', ['id'], unique=False)
    op.create_index(op.f('ix_instruction_steps_recipe_id'), 'instruction_steps', ['recipe_id'], unique=False)
    op.create_table('meal_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', pg.ENUM('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='mealtype', create_type=False), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('servings_planned', sa.Integer(), nullable=True),
    sa.Column('is_cooked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plans_id'), 'meal_plans', ['id'], unique=False)
    op.create_index(op.f('ix_meal_plans_user_id'), 'meal_plans', ['user_id'], unique=False)
    op.create_table('recipe_equipments',
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('equipment_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'equipment_id')
    )
    op.create_table('recipe_likes',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    op.create_table('recipe_tags',
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'tag_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_table('shopping_list_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('shopping_list_id', sa.String(), nullable=False),
    sa.Column('ingredient_id', sa.String(), nullable=True),
    sa.Column('custom_text', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('is_checked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_list_items_id'), 'shopping_list_items', ['id'], unique=False)
    op.create_index(op.f('ix_shopping_list_items_shopping_list_id'), 'shopping_list_items', ['shopping_list_id'], unique=False)
    op.add_column('recipe_ingredients', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('recipe_ingredients', sa.Column('display_text', sa.String(), nullable=True))
    op.add_column('recipe_ingredients', sa.Column('is_optional', sa.Boolean(), nullable=True))
    op.add_column('recipes', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('status', pg.ENUM('DRAFT', 'PUBLISHED', 'MODERATION', name='recipestatus', create_type=False), nullable=True))
    op.add_column('recipes', sa.Column('video_url', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('total_protein', sa.Float(), nullable=True))
    op.add_column('recipes', sa.Column('total_carbs', sa.Float(), nullable=True))
    op.add_column('recipes', sa.Column('total_fat', sa.Float(), nullable=True))
    op.add_column('recipes', sa.Column('servings', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('prep_time_minutes', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('cook_time_minutes', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('difficulty', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('author_id', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('recipes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recipes', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    op.create_index(op.f('ix_recipes_slug'), 'recipes', ['slug'], unique=True)
    op.create_index(op.f('ix_recipes_title'), 'recipes', ['title'], unique=False)
    op.create_foreign_key(None, 'recipes', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_index(op.f('ix_recipes_title'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_slug'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_column('recipes', 'deleted_at')
    op.drop_column('recipes', 'updated_at')
    op.drop_column('recipes', 'created_at')
    op.drop_column('recipes', 'author_id')
    op.drop_column('recipes', 'view_count')
    op.drop_column('recipes', 'difficulty')
    op.drop_column('recipes', 'cook_time_minutes')
    op.drop_column('recipes', 'prep_time_minutes')
    op.drop_column('recipes', 'servings')
    op.drop_column('recipes', 'total_fat')
    op.drop_column('recipes', 'total_carbs')
    op.drop_column('recipes', 'total_protein')
    op.drop_column('recipes', 'video_url')
    op.drop_column('recipes', 'status')
    op.drop_column('recipes', 'slug')
    op.drop_column('recipe_ingredients', 'is_optional')
    op.drop_column('recipe_ingredients', 'display_text')
    op.drop_column('recipe_ingredients', 'notes')
    op.drop_index(op.f('ix_shopping_list_items_shopping_list_id'), table_name='shopping_list_items')
    op.drop_index(op.f('ix_shopping_list_items_id'), table_name='shopping_list_items')
    op.drop_table('shopping_list_items')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('recipe_tags')
    op.drop_table('recipe_likes')
    op.drop_table('recipe_equipments')
    op.drop_index(op.f('ix_meal_plans_user_id'), table_name='meal_plans')
    op.drop_index(op.f('ix_meal_plans_id'), table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_instruction_steps_recipe_id'), table_name='instruction_steps')
    op.drop_index(op.f('ix_instruction_steps_id'), table_name='instruction_steps')
    op.drop_table('instruction_steps')
    op.drop_index(op.f('ix_cook_logs_id'), table_name='cook_logs')
    op.drop_table('cook_logs')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_table('collection_recipes')
    op.drop_table('user_profiles')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_shopping_lists_user_id'), table_name='shopping_lists')
    op.drop_index(op.f('ix_shopping_lists_id'), table_name='shopping_lists')
    op.drop_table('shopping_lists')
    op.drop_index(op.f('ix_search_logs_id'), table_name='search_logs')
    op.drop_table('search_logs')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_moderation_logs_id'), table_name='moderation_logs')
    op.drop_table('moderation_logs')
    op.drop_table('follows')
    op.drop_index(op.f('ix_collections_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('levels')
    op.drop_index(op.f('ix_equipments_name'), table_name='equipments')
    op.drop_index(op.f('ix_equipments_id'), table_name='equipments')
    op.drop_table('equipments')
    op.drop_table('badges')
    
    # Drop Enums manually
    sa.Enum('DRAFT', 'PUBLISHED', 'MODERATION', name='recipestatus').drop(op.get_bind())
    sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='mealtype').drop(op.get_bind())
    sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='skilllevel').drop(op.get_bind())
    sa.Enum('RECIPE', 'COMMENT', 'USER', name='entitytype').drop(op.get_bind())
    sa.Enum('APPROVE', 'REJECT', 'DELETE', name='moderationaction').drop(op.get_bind())
    sa.Enum('PENDING', 'RESOLVED', name='reportstatus').drop(op.get_bind())
    # ### end Alembic commands ###
