"""add_slug_to_entities

Revision ID: 239addcfca86
Revises: 282a684e6ba9
Create Date: 2026-03-19 19:17:26.731180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239addcfca86'
down_revision: Union[str, Sequence[str], None] = '282a684e6ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_collections_slug'), 'collections', ['slug'], unique=True)
    op.add_column('ingredients', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_ingredients_slug'), 'ingredients', ['slug'], unique=True)
    op.add_column('tags', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.add_column('users', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_slug'), 'users', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_slug'), table_name='users')
    op.drop_column('users', 'slug')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_column('tags', 'slug')
    op.drop_index(op.f('ix_ingredients_slug'), table_name='ingredients')
    op.drop_column('ingredients', 'slug')
    op.drop_index(op.f('ix_collections_slug'), table_name='collections')
    op.drop_column('collections', 'slug')
    # ### end Alembic commands ###
