"""Add category and diet_type to recipe metadata

Revision ID: 282a684e6ba9
Revises: 21adcfd72d12
Create Date: 2026-02-25 15:36:30.584353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282a684e6ba9'
down_revision: Union[str, Sequence[str], None] = '21adcfd72d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('category', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('diet_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'diet_type')
    op.drop_column('recipes', 'category')
    # ### end Alembic commands ###
