"""Add difficulty and category enums

Revision ID: bce94418bc79
Revises: c4e287bb6d03
Create Date: 2026-04-06 21:49:13.076233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce94418bc79'
down_revision: Union[str, Sequence[str], None] = 'c4e287bb6d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create Enums manually (Idempotent)
    op.execute("DO $$ BEGIN CREATE TYPE difficultylevel AS ENUM ('EASY', 'MEDIUM', 'HARD'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE recipecategory AS ENUM ('BREAKFAST', 'MAIN_COURSE', 'DESSERT', 'APPETIZER', 'SALAD', 'SOUP'); EXCEPTION WHEN duplicate_object THEN null; END $$;")

    # Clear existing data to avoid Enum conversion errors
    op.execute("DELETE FROM reviews;")
    op.execute("DELETE FROM comments;")
    op.execute("DELETE FROM recipe_likes;")
    op.execute("DELETE FROM recipe_ingredients;")
    op.execute("DELETE FROM instruction_steps;")
    op.execute("DELETE FROM recipe_tags;")
    op.execute("DELETE FROM recipes;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'difficulty',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'),
               existing_nullable=True,
               postgresql_using="UPPER(difficulty)::difficultylevel")
    op.alter_column('recipes', 'category',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('BREAKFAST', 'MAIN_COURSE', 'DESSERT', 'APPETIZER', 'SALAD', 'SOUP', name='recipecategory'),
               existing_nullable=True,
               postgresql_using="UPPER(category)::recipecategory")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'category',
               existing_type=sa.Enum('BREAKFAST', 'MAIN_COURSE', 'DESSERT', 'APPETIZER', 'SALAD', 'SOUP', name='recipecategory'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('recipes', 'difficulty',
               existing_type=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
